//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduate_work.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graduate_work.Localize.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user role.
        /// </summary>
        public static string ChangeUserRole {
            get {
                return ResourceManager.GetString("ChangeUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologize.
        /// </summary>
        public static string Denied_massege_1 {
            get {
                return ResourceManager.GetString("Denied_massege_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , but you do&apos;t have sufficient permissions to visit this page..
        /// </summary>
        public static string Denied_massege_2 {
            get {
                return ResourceManager.GetString("Denied_massege_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here is everything you might be interested in..
        /// </summary>
        public static string enticing_text {
            get {
                return ResourceManager.GetString("enticing text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate your password.
        /// </summary>
        public static string Exeption_Duplicate_your_password {
            get {
                return ResourceManager.GetString("Exeption_Duplicate your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date of birth specified.
        /// </summary>
        public static string Exeption_No_date_of_birth_specified {
            get {
                return ResourceManager.GetString("Exeption_No date of birth specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string Exeption_Passwords_do_not_match {
            get {
                return ResourceManager.GetString("Exeption_Passwords do not match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nickname is too short..
        /// </summary>
        public static string Exeption_The_nickname_is_too_short {
            get {
                return ResourceManager.GetString("Exeption_The nickname is too short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified character is longer than 10 characters, make it shorter..
        /// </summary>
        public static string Exeption_The_specified_character_is_longer_than_10_characters__make_it_shorter {
            get {
                return ResourceManager.GetString("Exeption_The specified character is longer than 10 characters, make it shorter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password is longer than 10 characters, make it shorter..
        /// </summary>
        public static string Exeption_The_specified_password_is_longer_than_10_characters__make_it_shorter_ {
            get {
                return ResourceManager.GetString("Exeption_The specified password is longer than 10 characters, make it shorter.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short..
        /// </summary>
        public static string Exeption_Too_short {
            get {
                return ResourceManager.GetString("Exeption_Too short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name not specified..
        /// </summary>
        public static string Exeption_User_name_not_specified {
            get {
                return ResourceManager.GetString("Exeption_User name not specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password not specified..
        /// </summary>
        public static string Exeption_User_password_not_specified_ {
            get {
                return ResourceManager.GetString("Exeption_User password not specified.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User pictures.
        /// </summary>
        public static string Gallery_UserPictures {
            get {
                return ResourceManager.GetString("Gallery_UserPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can register, add and view your pictures in the gallery and edit your profile, add comments, in the future I will add a new functionality for you..
        /// </summary>
        public static string Index_description {
            get {
                return ResourceManager.GetString("Index_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my website..
        /// </summary>
        public static string Index_greeting {
            get {
                return ResourceManager.GetString("Index_greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your best comment..
        /// </summary>
        public static string Index_Сomment {
            get {
                return ResourceManager.GetString("Index_Сomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Layout_dropdown {
            get {
                return ResourceManager.GetString("Layout_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Layout_gallery {
            get {
                return ResourceManager.GetString("Layout_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Layout_profile {
            get {
                return ResourceManager.GetString("Layout_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My project.
        /// </summary>
        public static string Layout_title {
            get {
                return ResourceManager.GetString("Layout_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Text.
        /// </summary>
        public static string Link_Text {
            get {
                return ResourceManager.GetString("Link Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging into the account:.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password:.
        /// </summary>
        public static string Login_EnterPassvord {
            get {
                return ResourceManager.GetString("Login_EnterPassvord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        public static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the user.
        /// </summary>
        public static string Profile_About_the_user {
            get {
                return ResourceManager.GetString("Profile_About the user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add avatar.
        /// </summary>
        public static string Profile_AddAvatar {
            get {
                return ResourceManager.GetString("Profile_AddAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event.
        /// </summary>
        public static string Profile_AddEvent {
            get {
                return ResourceManager.GetString("Profile_AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Profile_Comments {
            get {
                return ResourceManager.GetString("Profile_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link mail to your account.
        /// </summary>
        public static string Profile_LinkMail {
            get {
                return ResourceManager.GetString("Profile_LinkMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Comment.
        /// </summary>
        public static string Profile_Write_A_Comment {
            get {
                return ResourceManager.GetString("Profile_Write A Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comment.
        /// </summary>
        public static string Profile_Your_Comment {
            get {
                return ResourceManager.GetString("Profile_Your Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more.
        /// </summary>
        public static string read_more {
            get {
                return ResourceManager.GetString("read more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your date of birth:.
        /// </summary>
        public static string Registratio_date_of_birth_ {
            get {
                return ResourceManager.GetString("Registratio_date of birth:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your nickname:.
        /// </summary>
        public static string Registratio_nickname_ {
            get {
                return ResourceManager.GetString("Registratio_nickname:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password:.
        /// </summary>
        public static string Registratio_password {
            get {
                return ResourceManager.GetString("Registratio_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password again:.
        /// </summary>
        public static string Registratio_password_again {
            get {
                return ResourceManager.GetString("Registratio_password again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration_ {
            get {
                return ResourceManager.GetString("Registration_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string Show_Password {
            get {
                return ResourceManager.GetString("Show Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Source.
        /// </summary>
        public static string To_Source {
            get {
                return ResourceManager.GetString("To Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user role.
        /// </summary>
        public static string UserController_ChangeRole {
            get {
                return ResourceManager.GetString("UserController_ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the ID of the user whose role will be changed:.
        /// </summary>
        public static string UserController_ChangeRole_ChandeID {
            get {
                return ResourceManager.GetString("UserController_ChangeRole_ChandeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string UserController_ChangeRole_Roles {
            get {
                return ResourceManager.GetString("UserController_ChangeRole_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new role:.
        /// </summary>
        public static string UserController_ChangeRole_SelectRole {
            get {
                return ResourceManager.GetString("UserController_ChangeRole_SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserController_Login {
            get {
                return ResourceManager.GetString("UserController_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string UserController_Logout {
            get {
                return ResourceManager.GetString("UserController_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string View_Details {
            get {
                return ResourceManager.GetString("View Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website map.
        /// </summary>
        public static string Website_map {
            get {
                return ResourceManager.GetString("Website map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Comment.
        /// </summary>
        public static string Write_A_Comment {
            get {
                return ResourceManager.GetString("Write A Comment", resourceCulture);
            }
        }
    }
}
